
parameters:
  - name: checkoutRepos
    type: stepList
    default: []

  - name: blackduckViolationPolicy
    default: 'CRITICAL'

  - name: nugetConfigFile
    default: ''

  - name: developBranchTriggered
    default: ''

  - name: featureBranchTriggered
    default: ''

  - name: mainBranchTriggered
    default: ''

  - name: sastBranchTriggered
    default: ''
    
stages:
- stage: InitializeNugetCIStage
  displayName: Read NugetConfig Stage in CI
  jobs:
  - job: ReadNugetConfig
    displayName: Read Nuget Configs
    steps:
    - ${{ each repo in parameters.checkoutRepos }}:
      - ${{ each step in repo }}:
            ${{ step.key }}: ${{ step.value }}
    - task: PowerShell@2
      inputs:
        targetType: filePath
        filePath: .\main-pipeline-repo\nuget\v3\scripts\read-nuget-config.ps1
        arguments: >
          ${{parameters.developBranchTriggered}}
          ${{parameters.featureBranchTriggered}}
          ${{parameters.mainBranchTriggered}}
          ${{parameters.nugetConfigFile}}
          ${{parameters.sastBranchTriggered}}          
      name: sc 

#  - job: UpdatePipelineBuildNumber
#    dependsOn: ReadNugetConfig
#    variables:
#      solution: $[ dependencies.ReadNugetConfig.outputs['sc.param.solution'] ]
#    steps:
#    - template: templates/update-pipeline-build-number.yaml
#      parameters:
#        solution: $(solution)

- stage: SecurityCheckJob
  dependsOn: 
  - InitializeNugetCIStage
  displayName: CheckMarx Scan
  jobs:
  - job: FailIfCheckMarxThresholdIsInvalid
    condition: and( eq( stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.pipeline.checkMarxScan'], 'true') , notIn( stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.param.checkmarxThreshold'], 'STRICT', 'MODERATE'))
    steps:
    - script: |
        echo Failing this Job as CheckMarxThreshold value is invalid 
        exit 1
    
  - job: SecurityCheckJob
    condition: and( eq( stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.pipeline.checkMarxScan'], 'true') , in( stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.param.checkmarxThreshold'], 'STRICT', 'MODERATE'))
    variables:
      cxPreset: $[ stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.param.cxPreset'] ]
      projectName: $[ stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.param.cxProjectName'] ]
      checkmarxThreshold: $[ stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.param.checkmarxThreshold'] ]
      CxFolderExclusions: $[ stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.param.CxFolderExclusions'] ]
      solution: $[ stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.param.solution'] ]    
    displayName: 'Security check the source code'
    steps:
      - ${{ each repo in parameters.checkoutRepos }}:
        - ${{ each step in repo }}:
            ${{ step.key }}: ${{ step.value }}
      - template: ${{variables['System.DefaultWorkingDirectory']}}/devops-template/Naming_Standards.yml
      #Prepare dotnet core project
      - template: templates/checkmarx-nuget-restore.yaml
        parameters: 
          projectName: $(projectName)  
      - template: ${{variables['System.DefaultWorkingDirectory']}}/devops-template/Checkmarx.yml
        parameters:
          checkmarxThreshold: $(checkmarxThreshold)
          CxFolderExclusions: $(CxFolderExclusions)
         
- stage: BuildDotNet
  dependsOn: 
  - InitializeNugetCIStage
  - SecurityCheckJob
  displayName: Build Dot Net
  jobs:
  - job: BuildDotNet
    condition: and( eq( stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.pipeline.build'], 'true'), eq( stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.pipeline.sonarqubeScan'], 'false') )
    variables:
      solution: $[ stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.param.solution'] ]
      buildConfiguration: $[ stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.param.buildConfiguration'] ]
      projectName: $[ stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.param.projectName'] ]
    displayName: Build dotnet core project
    steps:
      - ${{ each repo in parameters.checkoutRepos }}:
        - ${{ each step in repo }}:
            ${{ step.key }}: ${{ step.value }}     
          
      #Prepare dotnet core project
      - template: templates/prepare-dotnet-core.yaml
        parameters: 
          projectName: $(projectName)
          solution: $(solution)
        
      #Build dotnet core project"
      - template: templates/build-dotnet-core.yaml
        parameters:
          solution: $(solution)
          buildConfiguration: $(buildConfiguration)

- stage: BuildDotNetWithSonar
  dependsOn: 
  - InitializeNugetCIStage
  - BuildDotNet
  displayName: Build Dot Net with SonarQube
  jobs:
  - job: FailIfSonarqubeThresholdIsInvalid
    condition: and( eq( stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.pipeline.sonarqubeScan'], 'true') , notIn( stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.param.sonarqubeThreshold'], 'STRICT', 'MODERATE'))
    steps:
    - script: |
        echo Failing this Job as sonarqubeThreshold value is invalid 
        exit 1

  - job: BuildDotNetSonar
    condition: and( eq( stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.pipeline.build'], 'true') , eq( stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.pipeline.sonarqubeScan'], 'true') , in( stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.param.sonarqubeThreshold'], 'STRICT', 'MODERATE'))
    variables:
      solution: $[ stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.param.solution'] ]
      buildConfiguration: $[ stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.param.buildConfiguration'] ]
      sonarqubeThreshold: $[ stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.param.sonarqubeThreshold'] ]
      projectName: $[ stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.param.projectName'] ]
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
        branchName: $[ variables['Build.SourceBranch'] ]
        pullRequestId: ""
      ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
        branchName: $[ variables['System.PullRequest.SourceBranch'] ]
        pullRequestId: $[ variables['System.PullRequest.PullRequestId'] ]      
    displayName: Build dotnet core project
    steps:
      - ${{ each repo in parameters.checkoutRepos }}:
        - ${{ each step in repo }}:
            ${{ step.key }}: ${{ step.value }}      
        
      #Prepare dotnet core project
      - template: templates/prepare-dotnet-core.yaml
        parameters:
          projectName: $(projectName)
          solution: $(solution)
        
      #Build dotnet core project"
      - template: templates/build-dotnet-core-Sonarqube.yaml
        parameters:
          solution: $(solution)
          buildConfiguration: $(buildConfiguration)
          branchName: $(branchName)
          pullRequestId: $(pullRequestId)
                    
- stage: BlackDuckScan
  dependsOn: 
  - InitializeNugetCIStage
  - BuildDotNetWithSonar
  displayName: BlackDuck Scan
  jobs:
  - job: BlackDuckScan
    condition: eq(stageDependencies['InitializeNugetCIStage']['ReadNugetConfig']['outputs']['sc.pipeline.blackDuckScan'], 'true')
    displayName: BlackDuck scan on built project
    steps:
      - ${{ each repo in parameters.checkoutRepos }}:
        - ${{ each step in repo }}:
              ${{ step.key }}: ${{ step.value }}      
  # Run the BlackDuck scan  
      - template: ${{variables['System.DefaultWorkingDirectory']}}/devops-template/Naming_Standards.yml        
      - template: ${{variables['System.DefaultWorkingDirectory']}}/devops-template/Synopsys.yml
        parameters:
          SnTimeOut: 2400
          SnServiceConnection: Synopsys (BlackDuck) - tfs9dec - Token Based
          SnDetectPolicy: ${{ parameters.blackduckViolationPolicy }}

- stage: 'PublishNuGetPackage'
  displayName: 'Publish NuGet Package'
  dependsOn: 
  - InitializeNugetCIStage
  - BlackDuckScan
  condition: succeeded()
  jobs:
  - job:
    displayName: Publish Nuget Package
    condition: eq( stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.pipeline.publishPackage'], 'true')
    variables:
      nupkgArtifactsPublishingPath: $[ stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.param.nupkgArtifactsPublishingPath'] ]
      zipArtifactsPublishingPath: $[ stageDependencies.InitializeNugetCIStage.ReadNugetConfig.outputs['sc.param.zipArtifactsPublishingPath'] ]
    steps:
    - download: current
      artifact: 'packages'    
    - task: ArtifactoryGenericUpload@2
      displayName: 'Publish Package in Artifactory'
      inputs:
        artifactoryService: 'Artifactory_GPS_BasicAuth'
        specSource: 'taskConfiguration'
        fileSpec: |
          {
            "files": [
              {             
                "pattern": "$(Pipeline.Workspace)/*.nupkg",
                "target": "$(nupkgArtifactsPublishingPath)"
              },
              {             
                "pattern": "$(Pipeline.Workspace)/*.zip",
                "target": "$(zipArtifactsPublishingPath)"
              }
            ]
          }
        collectBuildInfo: true
        failNoOp: true
        